In [3]:
import pandas as pd
import numpy as np

file_name='https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv'


df=pd.read_csv('https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv', header=0)

df.head(5)
df = df.fillna(0)
df    

df_drop= df.drop(['X', 'Y','OBJECTID','INCKEY','COLDETKEY', 'REPORTNO', 'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE', 'EXCEPTRSNDESC', 'SEVERITYDESC',
'COLLISIONTYPE','PERSONCOUNT','PEDCOUNT','PEDCYLCOUNT','VEHCOUNT', 'INCDATE','INCDTTM', 'JUNCTIONTYPE','SDOT_COLCODE', 'SDOT_COLDESC',
'INATTENTIONIND','UNDERINFL',
'PEDROWNOTGRNT', 'SDOTCOLNUM', 'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR', 'SPEEDING', 'SEVERITYCODE.1'], axis=1)

df_drop.dtypes

obj_df = df_drop.select_dtypes(include=['object','int']).copy()
obj_df.head()



obj_df["WEATHER"].value_counts()


obj_df['WEATHER'].isnull().values.any()

obj_df.reset_index(drop=True)

obj_df['WEATHER'].isnull().values.any()

cleanup_nums = {"WEATHER":     {"Clear": 1, "Raining": 2, "Overcast": 3, "Unknown": 4, "Snowing": 5, "Other": 6, "Fog/Smog/Smoke": 7,
                               "Sleet/Hail/Freezing Rain": 8, "Blowing Sand/Dirt": 9, "Severe Crosswind": 10,"Partly Cloudy": 11},
                "ROADCOND":    {"Dry": 1, "Wet": 2, "Unknown": 3, "Ice": 4,
                                  "Snow/Slush": 5, "Other": 6, "Standing Water": 7, "Sand/Mud/Dirt": 8,"Oil": 9},
               "LIGHTCOND":     {"Daylight": 1, "Dark - Street Lights On": 2, "Unknown": 3, "Dusk": 4, "Dawn": 5, "Dark - No Street Lights": 6, "Dark - Street Lights Off": 7,
                                 "Other": 8, "Dark - Unknown Lighting": 9}}
              



obj_df.replace(cleanup_nums, inplace= True)
obj_df.head()

obj_df["SEVERITYCODE"].value_counts()

import random 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans 
from sklearn.datasets.samples_generator import make_blobs 
%matplotlib inline

X = np.asarray(obj_df[['WEATHER', 'ROADCOND', 'LIGHTCOND']])
X[0:5]
  


Y=np.asarray(obj_df['SEVERITYCODE'])
Y[0:5]








/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


array([2, 1, 1, 1, 2])

In [4]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler 

X=preprocessing.StandardScaler().fit(X).transform (X)
X[0:5]
                                

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.15,train_size=0.85,random_state=3000)
print('train set', X_train.shape, Y_train.shape)
print('test set', X_test.shape, Y_test.shape)


train set (165472, 3) (165472,)
test set (29201, 3) (29201,)


/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [32]:
## DECISION TREE


#building dt
from sklearn.tree import DecisionTreeClassifier
DataTree= DecisionTreeClassifier (criterion="entropy", max_depth = 9)
DataTree
DataTree.fit (X_train, Y_train)

#train and predict
dtyhat= DataTree.predict (X_test)
print (dtyhat [0:5])
print (Y_test [0:5])

[1 1 1 1 1]
[1 1 2 1 1]


In [33]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, dtyhat)


0.7008664086846341

In [34]:

from sklearn.metrics import precision_recall_fscore_support
f1_score= precision_recall_fscore_support

f1_score(Y_test, dtyhat, average='macro')

(0.532314927278956, 0.5000580523239426, 0.41250769110713076, None)