In [1]:
import pandas as pd
import numpy as np

file_name='https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv'

df=pd.read_csv('https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv', header=0)

df = df.fillna(0)

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [2]:
df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  ... ROADCOND                LIGHTCOND  \
0  Matched  Intersection  37475.0  ...      Wet                 Daylight   
1  Matched         Block      0.0  ...      Wet  Dark - Street Lights On   
2  Matched         Block      0.0  ...      Dry                 Daylight   
3  Matched         Block      0.0  ...      Dry                 Daylight   
4  Matched  Intersection  34387.0  ...      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0             0         0.0        0         10   
1             0   6354039.0        0         11   
2             0   4323031.0        0         32   
3             0         0.0        0         23   
4             0   4028032.0        0         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

In [3]:
df1= df.drop(['X', 'Y','OBJECTID','INCKEY','COLDETKEY', 'REPORTNO', 'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION', 'EXCEPTRSNCODE', 'EXCEPTRSNDESC', 'SEVERITYDESC',
'COLLISIONTYPE','PERSONCOUNT','PEDCOUNT','PEDCYLCOUNT','VEHCOUNT', 'INCDATE','INCDTTM', 'JUNCTIONTYPE','SDOT_COLCODE', 'SDOT_COLDESC',
'INATTENTIONIND','UNDERINFL','PEDROWNOTGRNT', 'SDOTCOLNUM', 'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY', 'CROSSWALKKEY', 'HITPARKEDCAR', 
'SEVERITYCODE.1'], axis=1)

In [4]:
df1.head()

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND SPEEDING
0             2  Overcast      Wet                 Daylight        0
1             1   Raining      Wet  Dark - Street Lights On        0
2             1  Overcast      Dry                 Daylight        0
3             1     Clear      Dry                 Daylight        0
4             2   Raining      Wet                 Daylight        0

In [5]:
cleanup_nums = {"WEATHER":     {"Clear": 1, "Raining": 2, "Overcast": 3, "Unknown": 4, "Snowing": 5, "Other": 6, "Fog/Smog/Smoke": 7,
                               "Sleet/Hail/Freezing Rain": 8, "Blowing Sand/Dirt": 9, "Severe Crosswind": 10,"Partly Cloudy": 11},
                "ROADCOND":    {"Dry": 1, "Wet": 2, "Unknown": 3, "Ice": 4,
                                  "Snow/Slush": 5, "Other": 6, "Standing Water": 7, "Sand/Mud/Dirt": 8,"Oil": 9},
               "LIGHTCOND":     {"Daylight": 1, "Dark - Street Lights On": 2, "Unknown": 3, "Dusk": 4, "Dawn": 5, "Dark - No Street Lights": 6, "Dark - Street Lights Off": 7,
                                 "Other": 8, "Dark - Unknown Lighting": 9},
               "SPEEDING":  {"Y": 1, }}

In [6]:
df1.replace(cleanup_nums, inplace= True)
df1.head()

SEVERITYCODE  WEATHER  ROADCOND  LIGHTCOND  SPEEDING
0             2        3         2          1         0
1             1        2         2          2         0
2             1        3         1          1         0
3             1        1         1          1         0
4             2        2         2          1         0

In [7]:
df1.plot()

In [8]:
import random 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans 
from sklearn.datasets.samples_generator import make_blobs 
%matplotlib inline

In [14]:
X = np.asarray(df1[['WEATHER', 'ROADCOND', 'LIGHTCOND', 'SPEEDING']])
X[0:5]

array([[3, 2, 1, 0],
       [2, 2, 2, 0],
       [3, 1, 1, 0],
       [1, 1, 1, 0],
       [2, 2, 1, 0]])

In [18]:

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [19]:
X=preprocessing.StandardScaler().fit(X).transform (X)
X[0:5]


/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.12463013,  0.7333548 , -0.54513182, -0.22440165],
       [ 0.2413464 ,  0.7333548 ,  0.38082031, -0.22440165],
       [ 1.12463013, -0.54104269, -0.54513182, -0.22440165],
       [-0.64193733, -0.54104269, -0.54513182, -0.22440165],
       [ 0.2413464 ,  0.7333548 , -0.54513182, -0.22440165]])

In [22]:
Y=np.asarray(df1['SEVERITYCODE'])
Y[0:5]


array([2, 1, 1, 1, 2])

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,train_size=0.80,random_state=0)
print('train set', X_train.shape, Y_train.shape)
print('test set', X_test.shape, Y_test.shape)

train set (155738, 4) (155738,)
test set (38935, 4) (38935,)


In [33]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
k=25

In [34]:
neigh= KNeighborsClassifier(n_neighbors = k) .fit(X_train, Y_train)
neigh

kyhat= neigh.predict(X_test)

kyhat[0:5]

array([1, 1, 1, 1, 1])

In [35]:

from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, kyhat)

0.6998330550918197

In [37]:
from sklearn.metrics import precision_recall_fscore_support
f1_score= precision_recall_fscore_support